/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */
application {
    mainClassName = "reflection.App"
}

allprojects {
    repositories {
        jcenter()
    }
}

subprojects {
    version = "1.0"
}

plugins {
    java
    application
}
