package com.obelov.auxiliary.constructors

class AuxiliaryConstructorAutoGeneratedExample(
                                               val firstName: String = AuxiliaryConstructorExample.DEFAULT_FIRST_NAME,
                                               val lastName: String = AuxiliaryConstructorExample.DEFAULT_LAST_NAME,
                                               val sex: String = AuxiliaryConstructorExample.DEFAULT_SEX,
                                               val age: Int = AuxiliaryConstructorExample.DEFAULT_AGE
                                             ) {
}
