language: scala
before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh && jabba install "$TRAVIS_JDK" && jabba use $_ && java -version
script: sbt test

env:
  - TRAVIS_JDK=adopt@1.8.192-12
  - TRAVIS_JDK=adopt@1.11.0-1

matrix:
  fast_finish: true
  allow_failures:
    - env: TRAVIS_JDK=adopt@1.11.0-1 # not fully supported but allows problem discovery

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.jabba/jdk
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
